all:
	gcc-4.8 -fno-pie -fno-pie -fno-stack-protector -g3 -o exam1.1 exam1.1.c -static -m32
	gcc-4.8 -fno-pie -fno-pie -fno-stack-protector -g3 -o exam1 exam1.c -static -m32
	gcc-4.8 -fno-pie -fno-pie -fno-stack-protector -g3 -o exam2 exam2.c -static -m32 -falign-functions=60
	gcc-4.8 -fno-pie -fno-pie -fno-stack-protector -g3 -o exam3 exam3.c -static -m32
